### ISSUE TITLE
Establish procedure for calibrating hand motor joint limits

### ISSUE THREAD

**Issue by wxmerkt** [openhumanoids/valkyrie_translator#11]
- The joint limits in the URDF are for the actual joints and not the motor
- Motor limits for every finger motor except the thumb roll are (-0.3, 3.0), for the right thumb roll the limits are (0.0, 1.7); for the fingers, -0.3 is fully open, and 3.0 is fully closed [hat tip to @MathisFrankB]

**Comment by wxmerkt** [comment]
Procedure, on the test bench:
1. Edit the HandControl.yaml configuration file and set the min_limit to either -0.3 or 0 and the upper limit to 3
2. Compile and load the controller via the HandControl.launch launch file
3. Send joint position goal commands slowly increasing and record the highest value that closes the fingers to the desired maximum - save this value in the corresponding joint limit in the yaml configuration file
4. Commit and make a pull request

After #12, there are no further steps to this.

**Comment by mauricefallon** [comment]
This might fit into a wider "integrate lower arms" issue:
- update non-Drake robot urdf to have non-fixed joints. (currently I fix them when I create the file we use, but its easy to revert)
- Create a URDF to visualise the state of the entire lower arm in director
